name: magicsoup_dev

channels:
  - pytorch
  - nvidia
  - defaults

dependencies:
  - python=3.9
  - pip
  - pytorch
  - pytorch-cuda=11.6
  - pip:
      - build
      - -r src/requirements.txt
      - -r tests/requirements.txt
