[build-system]
requires = ["maturin>=1,<2"]
build-backend = "maturin"

[project]
name = "magicsoup" # as shown on PyPI (https://pypi.org/project/magicsoup/)
version = "2.0.0"
description = "MagicSoup is a game that simulates cell metabolic and transduction pathway evolution. Define a 2D world with certain molecules and reactions. Add a few cells and create evolutionary pressure by selectively replicating and killing them. Then run and see what random mutations can do."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
  "numpy>=2,<3",    # CPU processing  (necessary?)
  "torch>=2.11,<3", # CPU processing
]

[dependency-groups]
tests = [
  "maturin>=1,<2",                       # build and test python-rust packages
  "mkdocs>=1.5.3,<1.6.0",                # make documentation
  "mkdocstrings_python>=1.8.0,<2.0.0",   # make documentation from docstrings
  "mkdocstrings[python]>=0.24.0,<1.0.0", # documentation (necessary?)
  "Pygments>=2.14.0,<2.15.0",            # syntax highlighting
  "python-markdown-math>=0.8,<0.9",      # math in markdown
  "pytest>=9,<10",                       # testing
  "plotnine>=0,<1",                      # plotting
  "tensorboard>=2,<3",                   # watching simulation in browser
  "Levenshtein>=0,<1",                   # Levenshtein distance
  "mypy>=2,<3",                          # static type checking
]

[tool.maturin]
module-name = "magicsoup._lib"       # extension as imported from python
python-source = "python"             # source directory for python package
features = ["pyo3/extension-module"] # build as python extension module

[tool.uv.sources]
torch = [{ index = "pytorch-cpu" }]

[[tool.uv.index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true

[tool.pytest.ini_options]
pythonpath = [
  "./python", # Needed to resolve python package
]
markers = ["slow: marks tests as slow (deselect with '-m \"not slow\"')"]

[tool.pylint.main]
init-hook = 'import sys; sys.path.append("python")'

[tool.mypy]
mypy_path = [
  "./python", # Needed to resolve python package
]
namespace_packages = false
disable_error_code = "import-untyped"
