[build-system]
requires = ["maturin>=1,<2"]
build-backend = "maturin"

[project]
name = "magicsoup" # as shown on PyPI (https://pypi.org/project/magicsoup/)
version = "2.0.0"
authors = [{ name = "Marc", email = "schweringmarc01@gmail.com" }]
description = "Simulation for cell metabolic and transduction pathway evolution"
readme = "README.md"
requires-python = ">=3.12"
classifiers = [
  "Environment :: Console",
  "Environment :: GPU",
  "Intended Audience :: Science/Research",
  "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
  "Natural Language :: English",
  "Operating System :: OS Independent",
  "Programming Language :: Python :: 3",
  "Topic :: Education",
  "Topic :: Games/Entertainment",
  "Topic :: Scientific/Engineering",
  "Typing :: Typed",
]
dependencies = [
  "numpy>=2,<3",    # CPU processing  (necessary?)
  "torch>=2.11,<3", # CPU processing
]

[dependency-groups]
dev = [
  "maturin>=1,<2",     # build and test python-rust packages
  "pytest>=9,<10",     # testing
  "mypy>=2,<3",        # static type checking
  "ruff>=0,<1",        # linting
  "pylint>=4,<5",      # linting
  "plotnine>=0,<1",    # plotting
  "tensorboard>=2,<3", # watching simulation in browser
  "Levenshtein>=0,<1", # Levenshtein distance
]
docs = [
  "mkdocs>=1,<2",               # make documentation
  "python-markdown-math>=0,<1", # math in markdown
  "mkdocstrings[python]>=1,<2", # make documentation from docstrings
  "mkdocs-exclude>=1,<2",       # exclude files from documentation
]

[tool.maturin]
module-name = "magicsoup._lib"           # extension as imported from python
python-source = "python"                 # source directory for python package
features = ["pyo3/extension-module"]     # build as python extension module
sdist-include = ["LICENSE", "README.md"] # include license and readme in sdist

[tool.uv.sources]
torch = [{ index = "pytorch-cpu" }]

[[tool.uv.index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true

[tool.pytest.ini_options]
pythonpath = [
  "./python", # Needed to resolve python package
]
markers = ["slow: marks tests as slow (deselect with '-m \"not slow\"')"]

[tool.pylint.main]
init-hook = 'import sys; sys.path.append("python")'
extension-pkg-allow-list = "magicsoup._lib"

[tool.pylint.messages_control]
disable = ["C", "R"]

[tool.mypy]
mypy_path = [
  "./python", # Needed to resolve python package
]
namespace_packages = false
disable_error_code = "import-untyped"
